### ISSUE TITLE
Elasticsearch Rake task fails if resource index doesn't exist

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#57]
```2016-12-09 09:57:22 -0800: DELETE http://localhost:9200/resources [status:404, request:0.021s, query:N/A]
2016-12-09 09:57:22 -0800: < {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"resources","index_uuid":"_na_","index":"resources"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"resources","index_uuid":"_na_","index":"resources"},"status":404}
2016-12-09 09:57:22 -0800: [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"resources","index_uuid":"_na_","index":"resources"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"resources","index_uuid":"_na_","index":"resources"},"status":404}
rake aborted!
Elasticsearch::Transport::Transport::Errors::NotFound: [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"resources","index_uuid":"_na_","index":"resources"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"resources","index_uuid":"_na_","index":"resources"},"status":404}
/Users/pavan/.rvm/gems/ruby-2.3.2@commons/gems/elasticsearch-transport-5.0.0/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
/Users/pavan/.rvm/gems/ruby-2.3.2@commons/gems/elasticsearch-transport-5.0.0/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
/Users/pavan/.rvm/gems/ruby-2.3.2@commons/gems/elasticsearch-transport-5.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/pavan/.rvm/gems/ruby-2.3.2@commons/gems/elasticsearch-transport-5.0.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'
/Users/pavan/.rvm/gems/ruby-2.3.2@commons/gems/elasticsearch-api-5.0.0/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/Users/pavan/.rvm/gems/ruby-2.3.2@commons/gems/elasticsearch-api-5.0.0/lib/elasticsearch/api/actions/indices/delete.rb:44:in `delete'
/Users/pavan/Development/delete/commons/lib/tasks/elasticsearch.rake:7:in `block (2 levels) in <top (required)>'
/Users/pavan/.rvm/gems/ruby-2.3.2@commons/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/pavan/.rvm/gems/ruby-2.3.2@commons/bin/ruby_executable_hooks:15:in `eval'
/Users/pavan/.rvm/gems/ruby-2.3.2@commons/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => elasticsearch:reset_resource_index
(See full trace by running task with --trace)```

**Comment by T-Dnzt** [comment]
Not sure we want to rescue from this, I don't think it should happen at all. The index should exist before we run the task, right?
